version: '3.8'

services:
  web:
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=1
      - PHP_DISPLAY_STARTUP_ERRORS=1

  db:
    ports:
      - "3307:3306"  # Changed to use port 3307 instead of 3306
    environment:
      - MYSQL_ROOT_PASSWORD=timerbusinesstime
