version: '3.3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=timerbusinesstime
      - MYSQL_DATABASE=synced_watch

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=timerbusinesstime
      - MYSQL_DATABASE=synced_watch
    volumes:
      - mysql_data:/var/lib/mysql
      - ./timer_migration.sql:/docker-entrypoint-initdb.d/timer_migration.sql

volumes:
  mysql_data:
