version: '3.3'

services:
  web:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./ssl:/etc/apache2/ssl
      - ./apache-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - /etc/letsencrypt/live/waves.terrylongshore.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/waves.terrylongshore.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=timerbusinesstime
      - MYSQL_DATABASE=synced_watch

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=timerbusinesstime
      - MYSQL_DATABASE=synced_watch
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ./src/timer_migration.sql
        target: /docker-entrypoint-initdb.d/timer_migration.sql
        read_only: true

volumes:
  mysql_data:
